# PengantaR (Bagian 2)

### Mengakses elemen vektor

In [1]:
A <- seq(2,10, by=2)
A

[1]  2  4  6  8 10

In [2]:
A[c(1,2,3)]

[1] 2 4 6

In [3]:
A[1:3]

[1] 2 4 6

In [4]:
A[c(-1)] # tanpa indeks 1

[1]  4  6  8 10

In [5]:
A[c(-1,-2)] # tanpa indeks 1 dan 2

[1]  6  8 10

In [6]:
A[c(-1,-2,-3)] # tanpa indeks 1,2,dan 3

[1]  8 10

In [7]:
A[c(TRUE, FALSE, TRUE, TRUE, FALSE)]

[1] 2 6 8

Rangkuman:

* Kita dapat menggunakan `[]` untuk mengakses elemen vektor (*indexing* dimulai dari `1`).

* Nilai negatif digunakan untuk membuang elemen pada indeks yang tidak dikehendaki.

* Nilai - nilai Boolean, `TRUE` dan `FALSE` juga dapat digunakan untuk pengindeksan vektor.

### Mendefinisikan matriks

$$
A_{m,n} = 
\begin{pmatrix}
a_{1,1} & a_{1,2} & \cdots & a_{1,n} \\
a_{2,1} & a_{2,2} & \cdots & a_{2,n} \\
\vdots  & \vdots  & \ddots & \vdots  \\
a_{m,1} & a_{m,2} & \cdots & a_{m,n} 
\end{pmatrix}
$$

Sintaks : `matrix(data, nrow, ncol, byrow, dimnames)`

`data`: elemen - elemen di dalam matriks,

`nrow`: jumlah baris,

`ncols`: jumlah kolom,

`byrow`: Jika `TRUE`, maka elemen - elemen matriks akan disusun berdasarkan kolom

`dimnames`: Nama yg ditugaskan pada baris dan kolom.

contoh:

In [8]:
matrix(1:9, nrow=3, ncol=3)

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

In [9]:
matrix(1:9, nrow=3, ncol=3, byrow=TRUE)

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6   
[3,] 7    8    9

In [10]:
baris <- c('baris1', 'baris2', 'baris3')
kolom <- c('kolom1', 'kolom2', 'kolom3')

matrix(1:9, nrow=3, ncol=3, byrow=FALSE, dimnames = list(baris,kolom))

kolom1 kolom2 kolom3
baris1 1      4      7     
baris2 2      5      8     
baris3 3      6      9

### Mengakses elemen matriks

In [11]:
M = matrix(1:9, nrow=3, ncol=3)
M

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

Sintaks: `M[baris, kolom]`

In [12]:
M[1,1]

[1] 1

In [13]:
M[,1] # kolom 1

[1] 1 2 3

In [14]:
bar <- c('b1', 'b2', 'b3')
kol <- c('k1', 'k2', 'k3')

M <- matrix(1:9, nrow=3, ncol=3, dimnames=list(bar,kol))
M

k1 k2 k3
b1 1  4  7 
b2 2  5  8 
b3 3  6  9

In [15]:
M['b1', ] # baris 1

k1 k2 k3 
 1  4  7

In [16]:
M[1,]

k1 k2 k3 
 1  4  7

### DataFrame

<p align="justify">DataFrame adalah suatu tabel atau struktur berbentuk menyerupai <i>array</i> dua dimensi, di mana setiap kolomnya menyimpan data dari satu variabel dan setiap barisnya menyimpan data untuk suatu "titik" data yang sama dengan variabel yang berbeda - beda. Ibaratnya seperti <i>spreadsheet</i> MS Excel.</p>

Sintaks: `data.frame(#data)`

Contoh:

In [17]:
nama <- c('Sandy', 'Evelyn', 'Brenda')
umur <- c(43, 23, 45)
data.frame(nama,umur)

nama   umur
1 Sandy  43  
2 Evelyn 23  
3 Brenda 45

### Mengakses DataFrame 

In [18]:
nama <- c('Sandy', 'Evelyn', 'Brenda')
umur <- c(43, 23, 45)
gaji <- c(1000000, 9000000, 2000000)

D <- data.frame(nama,umur, gaji)
D

nama   umur gaji 
1 Sandy  43   1e+06
2 Evelyn 23   9e+06
3 Brenda 45   2e+06

Cara pertama:

In [19]:
D$nama # akses kolom nama dari dataframe D

[1] Sandy  Evelyn Brenda
Levels: Brenda Evelyn Sandy

In [20]:
D$nama[1] # baris pertama dari nama

[1] Sandy
Levels: Brenda Evelyn Sandy

Cara kedua:

In [21]:
D[1,] # mengakses baris pertama

nama  umur gaji 
1 Sandy 43   1e+06

In [22]:
D[c(1,2),] # akses seluruh kolom baris 1 - 2

nama   umur gaji 
1 Sandy  43   1e+06
2 Evelyn 23   9e+06

In [23]:
D$gaji <- D$gaji /(1e6) # membagi gaji sebanyak 10 dan menugaskan ulang ke dataframe

In [24]:
D

nama   umur gaji
1 Sandy  43   1   
2 Evelyn 23   9   
3 Brenda 45   2

In [25]:
# cara dapat intisari dataframe:

summary(D)

     nama        umur         gaji    
 Brenda:1   Min.   :23   Min.   :1.0  
 Evelyn:1   1st Qu.:33   1st Qu.:1.5  
 Sandy :1   Median :43   Median :2.0  
            Mean   :37   Mean   :4.0  
            3rd Qu.:44   3rd Qu.:5.5  
            Max.   :45   Max.   :9.0  

### Array

Array merupakan koleksi elemen - elemen multidimensional yang mempunyai tipe data seragam.

Sintaks: `array(data, dim, dimnames)`

Contoh:

In [9]:
print(array(data=c("who", 'am', 'I'), dim = c(3,3,2)))
# dim => 3 baris, 3 kolom, 2 level (2 matriks)

, , 1

     [,1]  [,2]  [,3] 
[1,] "who" "who" "who"
[2,] "am"  "am"  "am" 
[3,] "I"   "I"   "I"  

, , 2

     [,1]  [,2]  [,3] 
[1,] "who" "who" "who"
[2,] "am"  "am"  "am" 
[3,] "I"   "I"   "I"  



Harus diingat bahwa *array* harus punya tipe data **YANG SAMA**

In [10]:
bar <- c("B1", "B2", "B3")
kol <- c("K1", "K2", "K3")
mat <- c("M1", "M2")

print(array(data=c("halo","hai","hoi"), dim=c(3,3,2), dimnames=list(bar,kol,mat)))

, , M1

   K1     K2     K3    
B1 "halo" "halo" "halo"
B2 "hai"  "hai"  "hai" 
B3 "hoi"  "hoi"  "hoi" 

, , M2

   K1     K2     K3    
B1 "halo" "halo" "halo"
B2 "hai"  "hai"  "hai" 
B3 "hoi"  "hoi"  "hoi" 



### Mengakses array

In [8]:
bar <- c("B1", "B2", "B3")
kol <- c("K1", "K2", "K3")
mat <- c("M1", "M2")

A <- array(data=c("who","am","I"), dim=c(3,3,2), dimnames=list(bar,kol,mat))
print(A)

, , M1

   K1    K2    K3   
B1 "who" "who" "who"
B2 "am"  "am"  "am" 
B3 "I"   "I"   "I"  

, , M2

   K1    K2    K3   
B1 "who" "who" "who"
B2 "am"  "am"  "am" 
B3 "I"   "I"   "I"  



In [11]:
A[1,1,1] # A[baris, kolom, matriks]

[1] "who"

In [12]:
A[1,1,] # baris 1, kolom 1, semua matriks

M1    M2 
"who" "who"

In [13]:
A[1,,1] # baris 1, semua kolom, matriks 1

K1    K2    K3 
"who" "who" "who"

In [14]:
A["B1",,] # baris B1, semua kolom, semua matriks

M1  M2 
K1 who who
K2 who who
K3 who who

### Mengenal list

In [18]:
L = list("PNP", 1:3, TRUE, matrix(1:6, nrow=2), array(5:10, dim = c(3,3,2)))